baseURL = "https://zhxqian3.github.io/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "zhxqian3的小记"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"
