[[main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 1
[[main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 2
[[main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 3